import './globals.css'
import {Montserrat} from 'next/font/google'
import Navbar from './components/Navbar'
import 'tailwindcss/tailwind.css'


const montserrat=Montserrat({
  subsets:['latin'],
  variable:'--font-inter',
})


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${montserrat.variable} font-mont bg-light w-full min-h-screen`}>
      <body>
        <Navbar />
        {children}
        </body>
    </html>
  )
}
